version: '3.8'

services:
  inventory-service:
    build: ./services/inventory-service
    container_name: inventory-service
    ports:
      - "50051:50051"
    depends_on:
      - notification-service
    volumes:
      - ./proto:/app/proto
      - ./services/inventory-service/prisma:/app/prisma
      - inventory-db:/app/dev-db
    working_dir: /app
    command: npx ts-node src/server.ts
    environment:
      - DATABASE_URL=file:/app/dev-db/dev.db

  order-service:
    build: ./services/order-service
    container_name: order-service
    ports:
      - "50052:50052"
    depends_on:
      - inventory-service
    volumes:
      - ./proto:/app/proto
    working_dir: /app
    command: npx ts-node src/server.ts

  notification-service:
    build: ./services/notification-service
    container_name: notification-service
    ports:
      - "50053:50053"
    volumes:
      - ./proto:/app/proto
    working_dir: /app
    command: npx ts-node src/server.ts

volumes:
  inventory-db: